import type { Metadata } from "next";
import "./globals.css";
import PageWrapper from "@/components/templates/page-wrapper";
import { inter } from "@/theme/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
